### ISSUE TITLE
installation via composer miss-configured

### ISSUE THREAD

**Issue by MichalOrm** [abantecart/ups-php#15]
after using command:
composer require abantecart/ups-php 
library is downloaded and installed, but PHP doesent see it.

After further investigation i have found that \vendor\composer\autoload_psr4.php doesent have anything related with abantecart nor ups

What i have also done is:
- force autoload regenerate with command: dump-autoload 
- manually remove all vendor folder with: rm -rf vendor
- clean install with: composer install

Any other ideas how to use this library?

**Comment by abolabo** [comment]
https://github.com/abantecart/ups-php/issues/8#issuecomment-1837519483
