### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by florianschieder** [abantecart/ups-php#16]
Hello there,
we'd like to incorporate the composer package `ups-php` into our codebase.
Will `ups-php` stay published open source or are there plans to turn this into a private repository?
I'm asking because there is no license shipped with this repository and we want to avoid the visibility of this repository might change in the future.
Thank you!

**Comment by abolabo** [comment]
hi. 
yes, we plan to release new version soon.
License.txt will be there, MIT and code will be public always.
Feel free to use it.

**Comment by florianschieder** [comment]
Alright, thank you very much for the quick response!
