### ISSUE TITLE
Which host to use in production

### ISSUE THREAD

**Issue by evs-xsarus** [abantecart/ups-php#18]
The host in this API is wwwcie.ups.com which , for the locator, only supports.

// United States - Atlantis
// Canada - Toronto
// Germany - Neuss
// Mexico - Mexico City

Do you know which host to use for normal production?

**Comment by abolabo** [comment]
@evs-xsarus please see official api documentation
https://github.com/UPS-API/api-documentation/blob/main/Locator.yaml
