### ISSUE TITLE
Rating seems broken, Successful API call returns all NULL values for all entities

### ISSUE THREAD

**Issue by Noodleyman** [abantecart/ups-php#21]
testing out rating today, and although a valid API call is made and reports success, all returned results are NULL, thus none of the returned API data is available. seems a generic issue with this wrapper. 

Testing the exact same API call manually via CURL works correctly. 

Example:
![image](https://github.com/abantecart/ups-php/assets/10614018/bf85df89-f4f0-4ee2-9946-f9d3c4df8393)

same API call via CURL:
![image](https://github.com/abantecart/ups-php/assets/10614018/745f39dc-3520-4c0d-9cf2-364970e5d4ef)

**Comment by APanteleychuk** [comment]
@Noodleyman I have the same problem Did you find any solution?

**Comment by Noodleyman** [comment]
Nope, I abandoned use of this wrapped and just wrote my own in the end as I only have minimal use cases

**Comment by APanteleychuk** [comment]
@Noodleyman did you put your solution on git for public access? I think such a code would be useful to many users

**Comment by abolabo** [comment]
@APanteleychuk @Noodleyman please check this out first. Official repo is full of issues related to Rate API.
https://github.com/UPS-API/api-documentation/issues
Have no idea how UPS plan to implement it.

**Comment by abolabo** [comment]
Please see our extension as example  based on API here
https://github.com/abantecart/abantecart-src/tree/master/public_html/extensions/ups
