### ISSUE TITLE
Update Codebase by UPS Documentation

### ISSUE THREAD

**Issue by DemigodCode** [abantecart/ups-php#5]
Hi,

the ShipmentResults->PackageResults issue is fixed now in the documentation (https://github.com/UPS-API/api-documentation/pull/30).
Can you please update the package?

**Comment by abolabo** [comment]
Hi, 
yes, sure. will do asap.
Thank you for notice

**Comment by DemigodCode** [comment]
Doesn't work either. Tried it with openapi generator, too.
Seems like OpenApi/Swagger standard doesn't support a mix of oneOf with the same object as array and single object.

We've tried it with php and java, it didn't work for both generators. Think we have to wait until UPS releases a new API Version which fixes the issue or we have to overwrite the HttpClient and convert single-valued fields which should be an array to an array in this custom httpClient.
